@echo off
echo Killing old processes...
taskkill /F /IM uvicorn.exe /T 2>nul
taskkill /F /IM node.exe /T 2>nul

echo Starting AI Backend Server (local, port 8000)...
start cmd /k "cd server && ..\.venv\Scripts\python.exe main.py"

echo Starting Frontend...
cd client
echo Install dependencies (if needed)...
call npm install
echo Starting Vite...
npm run dev
